### ISSUE TITLE
Unit tests are failing

### ISSUE THREAD

**Issue by hegdemk2004** [rpgleparser/rpgleparser#79]
I am trying to build the RPGLE Parser on Mac. The build is failing with Unit testing errors. Any suggestions / fixes please..

[ERROR] Tests run: 400, Failures: 2, Errors: 0, Skipped: 1

Also noticed that many files are not found during Unit Test Run e.g. 
- java.io.FileNotFoundException: src/test/resources/org/rpgleparser/tests/directives/copy_interrupt.rpgle/CMQRFH2G.copy (Not a directory)
- java.io.FileNotFoundException: src/test/resources/org/rpgleparser/tests/directives/copy_comment_61.rpgle/AC00001.copy (Not a directory)
- java.io.FileNotFoundException: src/test/resources/org/rpgleparser/tests/precompile/copy_56.rpgle/parms.copy (Not a directory)

**Comment by ryaneberly** [comment]
@hegdemk2004 .  Thanks for the note.  These issues have been resolved in dev

**Comment by hegdemk2004** [comment]
Hi Ryan,
Thanks for addressing the issue. Re-tried now, still getting 1 test failure. Looks like a Line break issue.
I have a Mac, could it be because of some line ending character difference between platforms?

-------------------------------------------------------------------------------
Test set: org.rpgleparser.integration.TestFiles
-------------------------------------------------------------------------------
Tests run: 260, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 19.471 s <<< FAILURE! - in org.rpgleparser.integration.TestFiles
test[19src/test/resources/org/rpgleparser/tests/comments/parsing_err.rpgle](org.rpgleparser.integration.TestFiles)  Time elapsed: 0.05 s  <<< FAILURE!
org.junit.ComparisonFailure: 
Token lists do not match expected:<...COMMENTS_EOL_HIDDEN<[]
33723 >
ID         ...> but was:<...COMMENTS_EOL_HIDDEN<[
]
33723 >
ID         ...>
Regards,Mahesh
    at org.rpgleparser.integration.TestFiles.test(TestFiles.java:173)
Regards,Mahesh

    On Wednesday, April 21, 2021, 6:07:21 AM GMT+5:30, ryaneberly ***@***.***> wrote:  
 
 


@hegdemk2004 . Thanks for the note. These issues have been resolved in dev

**Comment by ryaneberly** [comment]
@hegdemk2004 .  That test used CRLF.   I changed it to LF.  I dont have a Mac but that should resolve it.

**Comment by hegdemk2004** [comment]
Thanks Ryan,
Still failing on the same unit test:
[ERROR] Failures: 
[ERROR]   TestFiles.test:173 Token lists do not match expected:<...COMMENTS_EOL_HIDDEN<[]
33723 >
ID         ...> but was:<...COMMENTS_EOL_HIDDEN<[
]
33723 >
ID         ...>
Sorry, I looked and even compared files.. but I am not really able to figure out where you fixed the CRLF to LF? 

Regards,Mahesh

    On Friday, April 23, 2021, 3:08:04 AM GMT+5:30, ryaneberly ***@***.***> wrote:  
 
 


@hegdemk2004 . That test used CRLF. I changed it to LF. I dont have a Mac but that should resolve it.

**Comment by ryaneberly** [comment]
Oops forgot to push it up.  Try now :)
